### ISSUE TITLE
Renommer la branche master à main

### ISSUE THREAD

**Issue by kaaloo** [dataforgoodfr/python_template#1]
Lors de l'initialisation du répertoire `git` le nom utilisé pour la première branche créée a traditionnellement été `master`.  Cependant, l'utilisation du nom `master` est devenu anachronique et peut heurter certaines sensibilités.   Il me semble que GitHub crée des nouveaux répos en utilisant le nom `main` depuis quelques années.  Adopter cette convention dans les répos D4G permettrait d'appuyer cette démarche auprès des bénévoles de la communauté.

**Comment by pagbrl** [comment]
Hello @kaaloo ! L'orga est configurée pour que tous les nouveaux repos créés utilisent main, je pense que ce repo a été créé localement et push ensuite. 
Je m'occupe de changer le nom de cette branche et je ferai une passe sur les repos s12 pour voir si c'est encore possible de changer

**Comment by kaaloo** [comment]
Super ! Merci pour ta réactivité 🙏👏🎉
